app/__init__.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_admin import Admin, AdminIndexView
from flask_login import LoginManager, current_user
from flask import current_app, redirect, url_for
from flask_bootstrap import Bootstrap


app = Flask(__name__)
app.debug = True
app.config.from_object("config")
app.config['SQLALCHEMY_DATABASE_URI'] = "mysql://root:root@localhost:3306/as-press?charset=utf8"
app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True

db = SQLAlchemy(app)
app_admin = Admin(app, name='testAdmin')

class AdminIndexView(AdminIndexView):
    def is_accessible(self):
        return current_user.is_authenticated() and current_user.confirmed

    def _handle_view(self, name, **kwargs):
        if not self.is_accessible():
            return redirect(url_for('auth.admin_login'))

#bootstrap = Bootstrap()
#app_admin = Admin(app, name='testAdmin', index_view=AdminIndexView())
#app_admin.base_template = 'layout.html'
#login_manager = LoginManager()
#login_manager.session_protection = 'strong'
#login_manager.login_view = 'auth.login'
#login_manager.init_app(app)

from app.views import test_flask
app.register_blueprint(test_flask, url_prefix='/v1/product')

import os.path
_dir = os.path.dirname(os.path.abspath(__file__))
app.template_folder = os.path.join(_dir, '../templates')
app.static_folder = os.path.join(_dir, '../static')

app/admin/__init__.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from flask import Blueprint
from flask_admin.contrib.sqla import ModelView
from .. import app_admin
from .. import db
from app.model.User import User

admin = Blueprint('admin', __name__)
app_admin.add_view(ModelView(User, db.session))

app/views/__init__.py
# -*- coding: utf-8 -*-
from flask import Blueprint

test_flask = Blueprint('test', __name__)

from . import views

app/views/views.py
# -*- coding: utf-8 -*-
#!/usr/bin/env python
from flask import render_template
from app.model.User import User
import json
from . import test_flask


@test_flask.route("/front")
def index():
    res = User.query.filter_by(id=1).first()
    result = {"id": res.id, "nick_name": res.name}
    return json.dumps(result)


@test_flask.route("/template")
def test_template():
    res = User.query.filter_by(id=1).first()
    result = {"id": res.id, "nick_name": res.name}
    return render_template("test.html", name=res.name)

templates/index.html
<html>
    <body>
        <div>
            <a href="{{ url_for('admin.index') }}">Go to admin!</a>
        </div>
    </body>
</html>

templates/my_master.html
{% extends 'admin/base.html' %}

{% block access_control %}
{% if current_user.is_authenticated %}
<div class="navbar-text btn-group pull-right">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
        <i class="glyphicon glyphicon-user"></i>
        {% if current_user.first_name -%}
        {{ current_user.first_name }}
        {% else -%}
        {{ current_user.email }}
        {%- endif %}<span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
        <li><a href="{{ url_for('security.logout') }}">Log out</a></li>
    </ul>
</div>
{% endif %}
{% endblock %}

templates/security/_macros.html
{% macro render_field_with_errors(field) %}

<div class="form-group">
    {{ field.label }} {{ field(class_='form-control', **kwargs)|safe }}
    {% if field.errors %}
    <ul>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endmacro %}

{% macro render_field(field) %}
<p>{{ field(class_='form-control', **kwargs)|safe }}</p>
{% endmacro %}

{% macro render_checkbox_field(field) -%}
<div class="form-group">
    <div class="checkbox">
        <label>
            {{ field(type='checkbox', **kwargs) }} {{ field.label }}
        </label>
    </div>
</div>
{%- endmacro %}

templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Register</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>
{% endif %}

templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
{% if messages %}
<ul class="flashes">
  {% for category, message in messages %}
  <li class="{{ category }}">{{ message }}</li>
  {% endfor %}
</ul>
{% endif %}
{%- endwith %}

templates/security/login_user.html
{% extends 'admin/master.html' %}
{% from "security/_macros.html" import render_field, render_field_with_errors, render_checkbox_field %}
{% include "security/_messages.html" %}
{% block body %}
{{ super() }}
<div class="row-fluid">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Login</h1>
        <div class="well">
            <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
                {{ login_user_form.hidden_tag() }}
                {{ render_field_with_errors(login_user_form.email) }}
                {{ render_field_with_errors(login_user_form.password) }}
                {{ render_checkbox_field(login_user_form.remember) }}
                {{ render_field(login_user_form.next) }}
                {{ render_field(login_user_form.submit, class="btn btn-primary") }}
            </form>
            <p>Not yet signed up? Please <a href="{{ url_for('security.register') }}">register for an account</a>.</p>
        </div>
    </div>
</div>
{% endblock body %}

templates/security/register_user.html
{% extends 'admin/master.html' %}
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
{% block body %}
{{ super() }}
<div class="row-fluid">
    <div class="col-sm-8 col-sm-offset-2">
        <h1>Register</h1>
        <div class="well">
            <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
                {{ register_user_form.hidden_tag() }}
                {{ render_field_with_errors(register_user_form.email) }}
                {{ render_field_with_errors(register_user_form.password) }}
                {% if register_user_form.password_confirm %}
                {{ render_field_with_errors(register_user_form.password_confirm) }}
                {% endif %}
                {{ render_field(register_user_form.submit, class="btn btn-primary") }}
            </form>
            <p>Already signed up? Please <a href="{{ url_for('security.login') }}">log in</a>.</p>
        </div>
    </div>
</div>
{% endblock body %}

templates/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!doctype html>
<title>Hello from Flask</title>
{% if name %}
  <h1>Hello {{ name }}!</h1>
{% else %}
  <h1>Hello World!</h1>
{% endif %}
</body>
</html>